name: Build-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
        working-directory: backend

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: backend/release.zip

  backend-deploy:
    runs-on: ubuntu-latest
    needs: backend-build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: elte-financial-investment-rest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_REST }}
          package: .

  frontend-check:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Use Node.js 18.x
       uses: actions/setup-node@v3
       with:
         node-version: 18.x
         cache: 'npm'
         cache-dependency-path: frontend/package-lock.json
     - run: npm ci
       working-directory: frontend
     - run: CI=false npm run build --if-present
       working-directory: frontend

  frontend-deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: frontend-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: frontend
    - name: Build application
      run: CI=false npm run build -- --prod
      working-directory: frontend
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elte-financial-investment-web'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_WEB }}
        package: './frontend/build'
